version: 2
updates:
# Composer: Code-Dependencies
- package-ecosystem: composer
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin

- package-ecosystem: composer
  target-branch: stable30
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]

- package-ecosystem: composer
  target-branch: stable29
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]

- package-ecosystem: composer
  target-branch: stable28
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]

# Composer: Tooling
- package-ecosystem: composer
  directories:
    - "/"
    - "/tests/integration"
    - "/vendor-bin/csfixer"
    - "/vendor-bin/mozart"
    - "/vendor-bin/phpunit"
    - "/vendor-bin/psalm"
    - "/vendor-bin/rector"
  commit-message:
    prefix: "ci"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin

# NPM: Code-Dependencies
- package-ecosystem: npm
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin

- package-ecosystem: npm
  target-branch: stable30
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]

- package-ecosystem: npm
  target-branch: stable29
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]

- package-ecosystem: npm
  target-branch: stable28
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
